name: Zowe CICS Client Auto Responder
# This workflow is triggered when a label is added to an issue.
on:
  issues:
    types: labeled

jobs:
  processLabelAction:
    name: Process Label Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hramos/respond-to-issue-based-on-label@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}